### ISSUE TITLE
Améliorer l'UX de la courbe des fruits

### ISSUE THREAD

**Issue by blucet** [dataveyes/3d-plantviewer#1]
Courbe des fruits : amélioration générale de l’UX pour désambiguïser les fruits et les intervalles.

Reprise de la courbe : retravailler l'UX générale pour lever l'ambiguité intervalles - noeuds. La préparer pour le futur.

**Comment by blucet** [comment]
@petitssoldats voici des petites specs pour compléter les maquettes sur ce sujet :

![image](https://user-images.githubusercontent.com/17005709/78033819-2eaae980-7367-11ea-8b71-ddc39de1d97b.png)

- [ ] L'axe des x passe en haut du graphe
- [ ] On affiche moins de taquets sur l'axe des x, pour ne pas surcharger la lecture (0, 137.5, et 360° seulement)
- [ ] En mode internoeuds, l'axe des x doit montrer les bornes suivantes :
   - valeur min arrondie aux 5 inférieurs (28 mm → 25 mm)
   - valeur max arrondie aux 5 supérieurs (46 mm → 50 mm)
   - un taquet avec la valeur moyenne
- [ ] En mode internoeuds, la ligne en pointillés marquant l'angle d'or doit disparaître
- [ ] L'axe des y montre maintenant des intervalles et non plus des organes (d'ailleurs la taille des points sur la courbe a été réduite pour éviter de confondre un point de la courbe et un organe)
- [ ] Au hover ou à la sélection d'un intervalle, les numéros des organes s'affichent au-dessus et en-dessous de la valeur
- [ ] Lorsque 2 panels sont affichés, l'interaction doit être mutualisée : elle déclenche les mêmes évènements sur les 2 panels :

![image](https://user-images.githubusercontent.com/17005709/78035636-a7ab4080-7369-11ea-95f9-75d951ef5bcb.png)

**Comment by petitssoldats** [comment]
[ ] - Appliquer les nouvelles couleurs de selection / hover a la vue 3d
