### ISSUE TITLE
À l'arrivée sur l'app sans panneau, le viewport est déformé. Il faut ajouter un panneau pour le corriger

### ISSUE THREAD

**Issue by blucet** [dataveyes/3d-plantviewer#15]
Le viewport est écrasé, il faut rajouter un panneau pour retrouver le bon ratio.

Viewport :
![image](https://user-images.githubusercontent.com/17005709/78154839-07265080-743d-11ea-98b0-0fea1a809d5e.png)

Mode photo :
![image](https://user-images.githubusercontent.com/17005709/78154989-31780e00-743d-11ea-8c9d-70234e144340.png)

Après :
![image](https://user-images.githubusercontent.com/17005709/78155009-389f1c00-743d-11ea-839f-df9e2cf7f984.png)

**Comment by petitssoldats** [comment]
en fait c'est a cause du material threejs de fruit, rien de grave

**Comment by blucet** [comment]
Pas encore ok :
1. Je vais sur https://db.romi-project.eu/viz/viewer/2019-02-01_13-18-32 et je rentre en mode photo
2. J'ajoute le deuxième panel
3. Dès que j'interagis avec la vue, par exemple un pan, le viewport se déforme

**Comment by petitssoldats** [comment]
Donc tu vois le bug qu'en photo ?

**Comment by blucet** [comment]
Oui mais c'est plus facile de se rendre compte des déformations avec les photos, donc peut-être que je rate qqch sur le viewport 3d.

**Comment by petitssoldats** [comment]
J'ai changé la detection de changement de taille du container, ca vient de là, je vais me pencher dessus
