### ISSUE TITLE
[Courbes] Revoir l'espacement autour des courbes + la valeur max des intervalles

### ISSUE THREAD

**Issue by blucet** [dataveyes/3d-plantviewer#21]
Ce n'est pas une bonne pratique de faire un n+1 ou n+2 sur l'intervalle max juste pour gagner de la place. En effet, comme on légende le dernier tick de l'axe, on peut facilement croire qu'on a détecté 32 intervalles alors qu'en vrai il n'y en a que 30.

- [x] Il faut remettre le max de l'axe des y à l'intervalle max des données, par +1 ou +2.

De plus, pour régler le problème d'espace et de wording, je propose :

- [x] réduire la hauteur de l'espace blanc sous la courbe, marqué par une double-flèche dans l'image (c'est pas grave que le cartouche vert du carrousel photo vienne superposer la courbe)
- [x] augmenter l'espace blanc en haut de la courbe, entre les deux taquets rouges de l'image (on peut utiliser l'espace gagné en bas, divisé en deux entre le haut et le bas). Cela permettra qu'il n'y ait pas de superposition entre le label "Intervals" et le hover sur le dernier intervalle

<img width="295" alt="Screenshot 2020-04-06 at 11 36 03" src="https://user-images.githubusercontent.com/17005709/78544841-0f92d880-77fb-11ea-8fcb-c90f80b684c3.png">

**Comment by petitssoldats** [comment]
![image](https://user-images.githubusercontent.com/867041/78689779-ff602380-78f6-11ea-9122-3e31428fcec9.png)

comme ca ?

**Comment by blucet** [comment]
@petitssoldats ça me paraît très bien !

**Comment by blucet** [comment]
J'ai deux nouveaux retours :

- [ ] Le premier intervalle est difficile à hover / sélectionner, car sa zone active est trop petite. Serait-il possible de la faire descendre un peu sous la courbe, pour faciliter le survol ?
![image](https://user-images.githubusercontent.com/17005709/78766012-0899d080-7989-11ea-85f7-b6337ecbb3f6.png)

***

- [ ] La ligne "Automated / Manuel" est trop proche des valeurs des angles (ou des mm), l'info n'est pas assez distincte. Il faudrait remonter un peu la ligne :
![image](https://user-images.githubusercontent.com/17005709/78766114-22d3ae80-7989-11ea-8b3a-271c483e3f6e.png)
