### ISSUE TITLE
La sélection d'intervalle est perdue quand je reviens du mode photo au mode 3d

### ISSUE THREAD

**Issue by blucet** [dataveyes/3d-plantviewer#27]
1. Je vais en mode photo
2. Je clique sur la courbe pour sélectionner un intervalle
3. Je quitte le mode photo : la sélection est perdue sur la 3d de la plante. Il ne faudrait pas.

**Comment by petitssoldats** [comment]
J'ai pas ca en local, sur quel scan ?

**Comment by blucet** [comment]
Sur tous les scans, par exemple http://localhost:3000/viewer/2019-02-01_13-35-42.

**Comment by petitssoldats** [comment]
j'arrive pas du tout a reproduire ce cas là
Tu pourrais me faire une video ?

**Comment by blucet** [comment]
https://www.dropbox.com/s/12b6rgdr0vxmhep/Screen%20Recording%202020-04-08%20at%2014.27.55.mov?dl=0

**Comment by petitssoldats** [comment]
ah, uniquement sur le viewport 3d, ok
