### ISSUE TITLE
[Panel de droite] Ajouter de l'espace pour améliorer la lisibilité

### ISSUE THREAD

**Issue by ludovicriffault** [dataveyes/3d-plantviewer#30]
![image](https://user-images.githubusercontent.com/1585885/78873265-e072a600-7a4a-11ea-9dd9-3f895436b035.png)

Je trouve que le haut des panneaux de droite est assez confus, ça manque de hiérarchie. 
Il faudrait renforcer le groupement des éléments en ajoutant de l'espace sous le titre pour aider l'utilisateur à bien associer les zones.

cc @antoine-venco

**Comment by ludovicriffault** [comment]
Est-ce qu'un léger fond derrière la légende dynamique (automated et manual) peut aider à bien dissocier les zones visuellement ?

**Comment by ludovicriffault** [comment]
![image](https://user-images.githubusercontent.com/1585885/78892207-3ce4be00-7a69-11ea-8a88-2fb4f00fc907.png)

Voilà ce que j'avais en tête

**Comment by ludovicriffault** [comment]
On espace un peu et on ajoute un fond sur la légende dynamique (même variable couleur que le fond du viewport 3D)

**Comment by blucet** [comment]
@ludovicriffault @petitssoldats mes retours :

- [ ] il faut centrer verticalement le texte dans le fond
- [ ] l'espace entre le titre et le fond me semble trop grand. La courbe est déjà très compactée et c'est difficile à justifier pour des utilisateurs avancés qui ont besoin du plus possible de lisibilité sur la courbe. Pourrai-t-on diminuer cet espace, maintenant que le fond fait bien la séparation ?

![image](https://user-images.githubusercontent.com/17005709/79197551-3754f280-7e32-11ea-9e7d-811f8a47774f.png)

**Comment by ludovicriffault** [comment]
Je pense qu'il faut conserver un spacing homogène de part et d'autre du
titre pour bien le séparer du contenu. L'effet "compressé" sur la version
précédente n'aidait pas l'utilisateur à scanner l'information et à isoler
les différentes zones.

Le mar. 14 avr. 2020 à 09:29, Benoît Lucet <notifications@github.com> a
écrit :
