### ISSUE TITLE
[Nombres] Ajouter une propriété CSS pour avoir des nombres tabulés

### ISSUE THREAD

**Issue by ludovicriffault** [dataveyes/3d-plantviewer#32]
Il faudrait ajouter : 

```css
font-variant-numeric: tabular-nums;
```
Pour avoir des nombres tabulés sur les axes, le hover et la légende dynamique.

**Comment by ludovicriffault** [comment]
![image](https://user-images.githubusercontent.com/1585885/78874713-16b12500-7a4d-11ea-8e5b-fca65a693b7f.png)

Tu peux enlever le `letter-spacing` ici car il ne sera plus nécessaire.

**Comment by blucet** [comment]
@ludovicriffault @petitssoldats le letter spacing a toujours l'air présent, non ?

![image](https://user-images.githubusercontent.com/17005709/79197477-12f91600-7e32-11ea-88a3-7fa4b53054c7.png)

**Comment by ludovicriffault** [comment]
Oui, mais c'est peut-être à cause de l'ajout d'une condition CSS pour les
nombres tabulés (qui dans le cas présent doit probablement être appliquée
aussi sur le texte non numérique). A vérifier.

Le mar. 14 avr. 2020 à 09:27, Benoît Lucet <notifications@github.com> a
écrit :

**Comment by blucet** [comment]
@ludovicriffault je te laisse clore si ok pour toi.

**Comment by ludovicriffault** [comment]
Il faut aussi ajouter la tabulation sur les nombres de la zone de légende
dynamique.

Le mar. 14 avr. 2020 à 11:38, Benoît Lucet <notifications@github.com> a
écrit :
